# Generated by Django 4.2.7 on 2025-09-06 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licenses', '0001_initial'),
        ('employees', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('DEVICE', '端末'), ('LICENSE', 'ライセンス')], help_text='返却種別', max_length=10)),
                ('expected_return_date', models.DateField(help_text='返却予定日')),
                ('return_reason', models.TextField(help_text='返却理由')),
                ('condition_notes', models.TextField(blank=True, help_text='状態・コンディション（端末の場合）')),
                ('status', models.CharField(choices=[('PENDING', '処理待ち'), ('APPROVED', '承認済み'), ('COMPLETED', '完了'), ('CANCELLED', 'キャンセル')], default='PENDING', help_text='ステータス', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='処理日時', null=True)),
                ('actual_return_date', models.DateField(blank=True, help_text='実際の返却日', null=True)),
                ('notes', models.TextField(blank=True, help_text='備考')),
                ('admin_notes', models.TextField(blank=True, help_text='管理者メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_assignment', models.ForeignKey(blank=True, help_text='返却対象端末割当', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='devices.deviceassignment')),
                ('employee', models.ForeignKey(help_text='申請者', on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='employees.employee')),
                ('license_assignment', models.ForeignKey(blank=True, help_text='返却対象ライセンス割当', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='licenses.licenseassignment')),
                ('processed_by', models.ForeignKey(blank=True, help_text='処理者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '返却申請',
                'verbose_name_plural': '返却申請',
                'db_table': 'return_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='return_requ_employe_38dfa1_idx'), models.Index(fields=['request_type', 'status'], name='return_requ_request_08cf4d_idx'), models.Index(fields=['expected_return_date'], name='return_requ_expecte_153d21_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('DEVICE', '端末'), ('LICENSE', 'ライセンス')], help_text='リクエスト種別', max_length=10)),
                ('device_type', models.CharField(blank=True, help_text='希望端末種別（端末申請の場合）', max_length=20)),
                ('software_name', models.CharField(blank=True, help_text='希望ソフトウェア名（ライセンス申請の場合）', max_length=200)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='詳細仕様・要件')),
                ('purpose', models.TextField(help_text='利用目的・理由')),
                ('business_justification', models.TextField(help_text='業務上の必要性')),
                ('expected_usage_period', models.CharField(help_text='利用予定期間', max_length=100)),
                ('expected_start_date', models.DateField(help_text='利用開始希望日')),
                ('expected_end_date', models.DateField(blank=True, help_text='利用終了予定日', null=True)),
                ('priority', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('URGENT', '緊急')], default='MEDIUM', help_text='優先度', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '承認待ち'), ('APPROVED', '承認済み'), ('REJECTED', '却下'), ('FULFILLED', '完了'), ('CANCELLED', 'キャンセル')], default='PENDING', help_text='ステータス', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='承認日時', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='却下理由')),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='完了日時', null=True)),
                ('notes', models.TextField(blank=True, help_text='備考')),
                ('admin_notes', models.TextField(blank=True, help_text='管理者メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='承認者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_resource_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='申請者', on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests', to='employees.employee')),
                ('fulfilled_by', models.ForeignKey(blank=True, help_text='完了処理者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_resource_requests', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_device', models.ForeignKey(blank=True, help_text='割り当てられた端末', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='devices.device')),
                ('fulfilled_license', models.ForeignKey(blank=True, help_text='割り当てられたライセンス', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='licenses.license')),
            ],
            options={
                'verbose_name': 'リソース申請',
                'verbose_name_plural': 'リソース申請',
                'db_table': 'resource_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='resource_re_employe_9bf61f_idx'), models.Index(fields=['request_type', 'status'], name='resource_re_request_138f83_idx'), models.Index(fields=['status', 'created_at'], name='resource_re_status_54c3ae_idx'), models.Index(fields=['expected_start_date'], name='resource_re_expecte_6a5359_idx')],
            },
        ),
    ]
