# Generated by Django 4.2.7 on 2025-09-06 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
        ('employees', '0001_initial'),
        ('devices', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('LICENSE_EXPIRY', 'ライセンス期限切れ'), ('ASSIGNMENT_EXPIRY', 'ライセンス割当期限切れ'), ('DEVICE_OVERDUE', '端末返却期限超過'), ('REQUEST_APPROVED', 'リクエスト承認'), ('REQUEST_REJECTED', 'リクエスト却下'), ('SYSTEM_ALERT', 'システムアラート')], help_text='通知種別', max_length=20)),
                ('title', models.CharField(help_text='通知タイトル', max_length=200)),
                ('message', models.TextField(help_text='通知メッセージ')),
                ('priority', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '緊急')], default='MEDIUM', help_text='優先度', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '未送信'), ('SENT', '送信済み'), ('READ', '既読'), ('DISMISSED', '無視')], default='PENDING', help_text='ステータス', max_length=20)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='送信予定日時')),
                ('sent_at', models.DateTimeField(blank=True, help_text='送信日時', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='既読日時', null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='無視日時', null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='追加データ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='通知対象社員', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employees.employee')),
                ('related_device', models.ForeignKey(blank=True, help_text='関連端末', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='devices.device')),
                ('related_license', models.ForeignKey(blank=True, help_text='関連ライセンス', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='licenses.license')),
                ('related_request', models.ForeignKey(blank=True, help_text='関連リソース申請', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboard.resourcerequest')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='notificatio_employe_cbc643_idx'), models.Index(fields=['notification_type', 'status'], name='notificatio_notific_21f913_idx'), models.Index(fields=['priority', 'scheduled_at'], name='notificatio_priorit_e531e1_idx'), models.Index(fields=['scheduled_at'], name='notificatio_schedul_2a5c00_idx')],
            },
        ),
    ]
