# Generated by Django 4.2.7 on 2025-09-04 12:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LAPTOP', 'ラップトップ'), ('DESKTOP', 'デスクトップ'), ('TABLET', 'タブレット'), ('SMARTPHONE', 'スマートフォン')], help_text='端末種別', max_length=20)),
                ('manufacturer', models.CharField(help_text='メーカー', max_length=100)),
                ('model', models.CharField(help_text='モデル', max_length=100)),
                ('serial_number', models.CharField(help_text='シリアル番号', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='シリアル番号は英数字とハイフンのみ使用可能です', regex='^[A-Z0-9\\-]+$')])),
                ('purchase_date', models.DateField(help_text='購入日')),
                ('warranty_expiry', models.DateField(help_text='保証期限')),
                ('status', models.CharField(choices=[('AVAILABLE', '利用可能'), ('ASSIGNED', '貸出中'), ('MAINTENANCE', '修理中'), ('DISPOSED', '廃棄')], default='AVAILABLE', help_text='ステータス', max_length=20)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='仕様情報 (CPU, メモリ, ストレージ等)')),
                ('notes', models.TextField(blank=True, help_text='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_devices', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '端末',
                'verbose_name_plural': '端末',
                'db_table': 'devices',
                'ordering': ['type', 'manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(help_text='割当日')),
                ('expected_return_date', models.DateField(blank=True, help_text='返却予定日', null=True)),
                ('actual_return_date', models.DateField(blank=True, help_text='実際の返却日', null=True)),
                ('purpose', models.CharField(help_text='使用目的', max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'アクティブ'), ('RETURNED', '返却済み'), ('OVERDUE', '期限超過')], default='ACTIVE', help_text='ステータス', max_length=20)),
                ('assignment_notes', models.TextField(blank=True, help_text='割当時の備考')),
                ('return_notes', models.TextField(blank=True, help_text='返却時の備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='割当実行者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(help_text='割り当て端末', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='devices.device')),
                ('employee', models.ForeignKey(help_text='割り当て社員', on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='employees.employee')),
                ('returned_by', models.ForeignKey(blank=True, help_text='返却処理者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '端末割当',
                'verbose_name_plural': '端末割当',
                'db_table': 'device_assignments',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['device', '-assigned_date'], name='device_assi_device__4a7b48_idx'), models.Index(fields=['employee', '-assigned_date'], name='device_assi_employe_a1e602_idx'), models.Index(fields=['status'], name='device_assi_status_8d87b6_idx'), models.Index(fields=['assigned_date'], name='device_assi_assigne_8aeeae_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='deviceassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('device',), name='unique_active_device_assignment'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['type'], name='devices_type_e90211_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_status_9f14cf_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='devices_serial__9114fa_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['manufacturer'], name='devices_manufac_541a3d_idx'),
        ),
    ]
