# Generated by Django 4.2.7 on 2025-09-06 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('USAGE_STATS', '利用状況統計'), ('INVENTORY_STATUS', '在庫状況'), ('COST_ANALYSIS', 'コスト分析'), ('DEPARTMENT_USAGE', '部署別利用状況'), ('POSITION_USAGE', '役職別利用状況')], help_text='レポート種別', max_length=20)),
                ('report_key', models.CharField(help_text='レポートキー（パラメータのハッシュ）', max_length=200)),
                ('data', models.JSONField(help_text='キャッシュされたレポートデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='キャッシュ有効期限')),
            ],
            options={
                'verbose_name': 'レポートキャッシュ',
                'verbose_name_plural': 'レポートキャッシュ',
                'db_table': 'report_cache',
                'indexes': [models.Index(fields=['report_type', 'report_key'], name='report_cach_report__f98eb3_idx'), models.Index(fields=['expires_at'], name='report_cach_expires_283898_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reportcache',
            constraint=models.UniqueConstraint(fields=('report_type', 'report_key'), name='unique_report_cache'),
        ),
    ]
