# Generated by Django 4.2.7 on 2025-09-04 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionoverride',
            name='effective_from',
            field=models.DateField(default=datetime.date.today, help_text='有効開始日'),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='effective_from',
            field=models.DateField(default=datetime.date.today, help_text='有効開始日'),
        ),
    ]
