# Generated by Django 4.2.7 on 2025-09-04 12:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(help_text='社員ID (例: EMP001, TOKYO001)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='社員IDは3-20文字の英数字（大文字）で入力してください', regex='^[A-Z0-9]{3,20}$')])),
                ('name', models.CharField(help_text='氏名', max_length=100)),
                ('name_kana', models.CharField(blank=True, help_text='氏名（カナ）', max_length=100)),
                ('email', models.EmailField(help_text='メールアドレス', max_length=254, unique=True)),
                ('department', models.CharField(help_text='部署', max_length=100)),
                ('position', models.CharField(help_text='役職', max_length=100)),
                ('location', models.CharField(choices=[('TOKYO', '東京'), ('OKINAWA', '沖縄'), ('REMOTE', 'リモート')], help_text='勤務地', max_length=10)),
                ('hire_date', models.DateField(help_text='入社日')),
                ('termination_date', models.DateField(blank=True, help_text='退職日', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'アクティブ'), ('INACTIVE', '非アクティブ')], default='ACTIVE', help_text='ステータス', max_length=10)),
                ('phone_number', models.CharField(blank=True, help_text='電話番号', max_length=20, validators=[django.core.validators.RegexValidator(message='有効な電話番号を入力してください', regex='^[\\d\\-\\+\\(\\)\\s]+$')])),
                ('emergency_contact_name', models.CharField(blank=True, help_text='緊急連絡先（氏名）', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='緊急連絡先（電話番号）', max_length=20, validators=[django.core.validators.RegexValidator(message='有効な電話番号を入力してください', regex='^[\\d\\-\\+\\(\\)\\s]+$')])),
                ('notes', models.TextField(blank=True, help_text='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='関連するユーザーアカウント', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '社員',
                'verbose_name_plural': '社員',
                'db_table': 'employees',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('CREATE', '作成'), ('UPDATE', '更新'), ('TERMINATION', '退職'), ('REACTIVATION', '復職'), ('DEPARTMENT_CHANGE', '部署変更'), ('POSITION_CHANGE', '役職変更'), ('LOCATION_CHANGE', '勤務地変更')], help_text='変更種別', max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='変更フィールド名', max_length=50)),
                ('old_value', models.TextField(blank=True, help_text='変更前の値')),
                ('new_value', models.TextField(blank=True, help_text='変更後の値')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='備考')),
                ('changed_by', models.ForeignKey(blank=True, help_text='変更者', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='対象社員', on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='employees.employee')),
            ],
            options={
                'verbose_name': '社員履歴',
                'verbose_name_plural': '社員履歴',
                'db_table': 'employee_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['employee', '-changed_at'], name='employee_hi_employe_7e08b0_idx'), models.Index(fields=['change_type'], name='employee_hi_change__653b9a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_employe_0b5eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employees_departm_ef7a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='employees_status_0192ac_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['location'], name='employees_locatio_eb5492_idx'),
        ),
    ]
